/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veterinaria;

/**
 *
 * @author SantiagoRojasColunge
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelNames = new javax.swing.JLabel();
        jLabelLastNames = new javax.swing.JLabel();
        jLabelPetType = new javax.swing.JLabel();
        jLabelPetName = new javax.swing.JLabel();
        jLabelMail = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jLabelDocument = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        jTextFieldNames = new javax.swing.JTextField();
        jTextFieldLastNames = new javax.swing.JTextField();
        jTextFieldPetName = new javax.swing.JTextField();
        jComboBoxPetType = new javax.swing.JComboBox<>();
        jTextFieldMail = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jTextFieldDocument = new javax.swing.JTextField();
        jTextFieldPasword = new javax.swing.JTextField();
        BTNLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(480, 480));
        setMinimumSize(new java.awt.Dimension(480, 480));
        setPreferredSize(new java.awt.Dimension(480, 480));

        jPanel1.setMaximumSize(new java.awt.Dimension(480, 480));
        jPanel1.setMinimumSize(new java.awt.Dimension(480, 480));
        jPanel1.setPreferredSize(new java.awt.Dimension(480, 480));
        jPanel1.setLayout(null);

        jLabelUserName.setText("Nombre de Usuario: ");
        jPanel1.add(jLabelUserName);
        jLabelUserName.setBounds(52, 34, 115, 16);

        jLabelNames.setText("Nombres: ");
        jPanel1.add(jLabelNames);
        jLabelNames.setBounds(52, 76, 58, 16);

        jLabelLastNames.setText("Apellidos: ");
        jPanel1.add(jLabelLastNames);
        jLabelLastNames.setBounds(52, 118, 58, 16);

        jLabelPetType.setText("Tipo de mascota: ");
        jPanel1.add(jLabelPetType);
        jLabelPetType.setBounds(52, 160, 100, 16);

        jLabelPetName.setText("Nombre de la Mascota: ");
        jPanel1.add(jLabelPetName);
        jLabelPetName.setBounds(52, 207, 133, 16);

        jLabelMail.setText("Correo electronico: ");
        jPanel1.add(jLabelMail);
        jLabelMail.setBounds(52, 245, 112, 16);

        jLabelPhone.setText("Celular: ");
        jPanel1.add(jLabelPhone);
        jLabelPhone.setBounds(52, 287, 46, 16);

        jLabelDocument.setText("Documento: ");
        jPanel1.add(jLabelDocument);
        jLabelDocument.setBounds(52, 329, 71, 16);

        jLabelPassword.setText("Contraseña: ");
        jPanel1.add(jLabelPassword);
        jLabelPassword.setBounds(52, 371, 72, 16);
        jPanel1.add(UserName);
        UserName.setBounds(200, 30, 153, 24);
        jPanel1.add(jTextFieldNames);
        jTextFieldNames.setBounds(200, 72, 153, 24);
        jPanel1.add(jTextFieldLastNames);
        jTextFieldLastNames.setBounds(200, 114, 153, 24);
        jPanel1.add(jTextFieldPetName);
        jTextFieldPetName.setBounds(203, 203, 153, 24);

        jComboBoxPetType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBoxPetType);
        jComboBoxPetType.setBounds(203, 155, 150, 26);
        jPanel1.add(jTextFieldMail);
        jTextFieldMail.setBounds(203, 245, 153, 24);
        jPanel1.add(jTextFieldPhone);
        jTextFieldPhone.setBounds(203, 287, 153, 24);
        jPanel1.add(jTextFieldDocument);
        jTextFieldDocument.setBounds(203, 329, 153, 24);
        jPanel1.add(jTextFieldPasword);
        jTextFieldPasword.setBounds(203, 371, 153, 24);

        BTNLogin.setText("Registrarse");
        BTNLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLoginActionPerformed(evt);
            }
        });
        jPanel1.add(BTNLogin);
        BTNLogin.setBounds(190, 413, 97, 32);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login_wall.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(480, 480));
        jLabel1.setMinimumSize(new java.awt.Dimension(480, 480));
        jLabel1.setPreferredSize(new java.awt.Dimension(480, 480));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(2, -3, 480, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLoginActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNLogin;
    private javax.swing.JTextField UserName;
    private javax.swing.JComboBox<String> jComboBoxPetType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDocument;
    private javax.swing.JLabel jLabelLastNames;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelNames;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPetName;
    private javax.swing.JLabel jLabelPetType;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldDocument;
    private javax.swing.JTextField jTextFieldLastNames;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldNames;
    private javax.swing.JTextField jTextFieldPasword;
    private javax.swing.JTextField jTextFieldPetName;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables
}
